spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ex_2020011242
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '030326'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

server:
  port: 9000


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


